assets:
  rubygems.yml: zerocracy/home#assets/rubygems.yml
  s3cfg: zerocracy/home#assets/s3cfg
install: |
  sudo gem install --no-ri --no-rdoc pdd
  sudo apt-get install -y subversion diffstat
  sudo apt-get install -y software-properties-common
  sudo add-apt-repository -y ppa:git-core/ppa
  sudo apt-get update
  sudo apt-get remove -y git
  sudo apt-get install -y git
deploy:
  script: |
    sudo bundle install
    rake
release:
  script: |
    pdd --verbose --file=/dev/null
    bundle install
    rake
    rm -rf *.gem
    sed -i "s/1\.0\.snapshot/${tag}/g" lib/hoc/version.rb
    git commit -m "${tag}" lib/hoc/version.rb
    gem build hoc.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
